name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8d309919c42bafae45c74447d5bc27a12e4f8380179b2e7a0e12f542c281558"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
