name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f58419a9d19cb1889553ef1b17335472d7f1ab72f6f0e31c18f38786d862626a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
