name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b432a7e34822de6ef8b498495edc71e6c979f8f90e6f1684fc8c14b46492b318"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
