name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f265a36ab35c3b5b0945ba7c7a7cb1ad677c0e2f3df643e3795e5d6376cf886b"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
