name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "894f86aa6e154698b3d36b22ce2be78352c48c99f8eafb65468a47ff2319f997"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
