name = "Devs.SMP"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c037cb6db0d275f5783d25e44e7b911f4649e66f4453dab5cbf365057871a11e"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
